//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISEE.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ISEE.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iSEE enables spatial management vision by cross-referencing the geographical information provided by the company’s sales representatives with other business data, providing a broader combined marketing and operations oriented perspective..
        /// </summary>
        public static string AboutString {
            get {
                return ResourceManager.GetString("AboutString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add An Info.
        /// </summary>
        public static string AddInfo {
            get {
                return ResourceManager.GetString("AddInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Employee.
        /// </summary>
        public static string AddNewEmployee {
            get {
                return ResourceManager.GetString("AddNewEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddNode.
        /// </summary>
        public static string AddNode {
            get {
                return ResourceManager.GetString("AddNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed  write error.
        /// </summary>
        public static string AddRequestFaild {
            get {
                return ResourceManager.GetString("AddRequestFaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to root.
        /// </summary>
        public static string AddToRoot {
            get {
                return ResourceManager.GetString("AddToRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Password.
        /// </summary>
        public static string AdminPassword {
            get {
                return ResourceManager.GetString("AdminPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adress.
        /// </summary>
        public static string Adress {
            get {
                return ResourceManager.GetString("Adress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        public static string AgrementCustomer {
            get {
                return ResourceManager.GetString("AgrementCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All groups.
        /// </summary>
        public static string All_Groups {
            get {
                return ResourceManager.GetString("All_Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Groups.
        /// </summary>
        public static string AllGroups {
            get {
                return ResourceManager.GetString("AllGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apartment.
        /// </summary>
        public static string Apartment {
            get {
                return ResourceManager.GetString("Apartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit from application. Are you sure?.
        /// </summary>
        public static string ApplicationExit {
            get {
                return ResourceManager.GetString("ApplicationExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Result Search.
        /// </summary>
        public static string BefowSearch {
            get {
                return ResourceManager.GetString("BefowSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main box.
        /// </summary>
        public static string BoxMain {
            get {
                return ResourceManager.GetString("BoxMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building Number.
        /// </summary>
        public static string BuildingNum {
            get {
                return ResourceManager.GetString("BuildingNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobil.
        /// </summary>
        public static string Cel {
            get {
                return ResourceManager.GetString("Cel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center city.
        /// </summary>
        public static string CenterCity {
            get {
                return ResourceManager.GetString("CenterCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Adress.
        /// </summary>
        public static string ChangeAdress {
            get {
                return ResourceManager.GetString("ChangeAdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colors.
        /// </summary>
        public static string Colors {
            get {
                return ResourceManager.GetString("Colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Details.
        /// </summary>
        public static string CompanyDetails {
            get {
                return ResourceManager.GetString("CompanyDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Employee.
        /// </summary>
        public static string ContactEmployee {
            get {
                return ResourceManager.GetString("ContactEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Mail.
        /// </summary>
        public static string ContactMail {
            get {
                return ResourceManager.GetString("ContactMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent.
        /// </summary>
        public static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrentDate.
        /// </summary>
        public static string CurrentDate {
            get {
                return ResourceManager.GetString("CurrentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Note.
        /// </summary>
        public static string CusRemark1 {
            get {
                return ResourceManager.GetString("CusRemark1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary Customer Note.
        /// </summary>
        public static string CusRemark2 {
            get {
                return ResourceManager.GetString("CusRemark2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Info.
        /// </summary>
        public static string CustomerDetailsLabel {
            get {
                return ResourceManager.GetString("CustomerDetailsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Number.
        /// </summary>
        public static string CustomerNum {
            get {
                return ResourceManager.GetString("CustomerNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building Data.
        /// </summary>
        public static string CustomerToBuinding {
            get {
                return ResourceManager.GetString("CustomerToBuinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter date.
        /// </summary>
        public static string DateWatermarkContent {
            get {
                return ResourceManager.GetString("DateWatermarkContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day Status.
        /// </summary>
        public static string DayStatus {
            get {
                return ResourceManager.GetString("DayStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Leaf.
        /// </summary>
        public static string DeleteLeaf {
            get {
                return ResourceManager.GetString("DeleteLeaf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteNode.
        /// </summary>
        public static string DeleteNode {
            get {
                return ResourceManager.GetString("DeleteNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag Item To Tree.
        /// </summary>
        public static string DragItemToTree {
            get {
                return ResourceManager.GetString("DragItemToTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Details.
        /// </summary>
        public static string EditDetails {
            get {
                return ResourceManager.GetString("EditDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diary.
        /// </summary>
        public static string EmpDiary {
            get {
                return ResourceManager.GetString("EmpDiary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Info.
        /// </summary>
        public static string EmplDetails {
            get {
                return ResourceManager.GetString("EmplDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        public static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee groups.
        /// </summary>
        public static string Employee_groups {
            get {
                return ResourceManager.GetString("Employee_groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee_help.
        /// </summary>
        public static string Employee_help {
            get {
                return ResourceManager.GetString("Employee_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Number.
        /// </summary>
        public static string Employee_N {
            get {
                return ResourceManager.GetString("Employee_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string EmployeeCustomerContact {
            get {
                return ResourceManager.GetString("EmployeeCustomerContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visiting Employee.
        /// </summary>
        public static string EmpToCustomer {
            get {
                return ResourceManager.GetString("EmpToCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string EndDay {
            get {
                return ResourceManager.GetString("EndDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Time.
        /// </summary>
        public static string EndDayTime {
            get {
                return ResourceManager.GetString("EndDayTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry.
        /// </summary>
        public static string Entry {
            get {
                return ResourceManager.GetString("Entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Error.
        /// </summary>
        public static string ErrorLogIn {
            get {
                return ResourceManager.GetString("ErrorLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing Employee.
        /// </summary>
        public static string ExistEmployee {
            get {
                return ResourceManager.GetString("ExistEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Options.
        /// </summary>
        public static string ExpHeader {
            get {
                return ResourceManager.GetString("ExpHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string FactoryName {
            get {
                return ResourceManager.GetString("FactoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        public static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill Employee Hours.
        /// </summary>
        public static string FillEmployeeHours {
            get {
                return ResourceManager.GetString("FillEmployeeHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company name.
        /// </summary>
        public static string FirstNameCus {
            get {
                return ResourceManager.GetString("FirstNameCus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flip.
        /// </summary>
        public static string Flip {
            get {
                return ResourceManager.GetString("Flip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor.
        /// </summary>
        public static string Floor {
            get {
                return ResourceManager.GetString("Floor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        public static string Fri {
            get {
                return ResourceManager.GetString("Fri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Address.
        /// </summary>
        public static string FullAddress {
            get {
                return ResourceManager.GetString("FullAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to add new item.
        /// </summary>
        public static string GridViewAlwaysVisibleNewRow {
            get {
                return ResourceManager.GetString("GridViewAlwaysVisibleNewRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Filter.
        /// </summary>
        public static string GridViewClearFilter {
            get {
                return ResourceManager.GetString("GridViewClearFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string GridViewFilter {
            get {
                return ResourceManager.GetString("GridViewFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And.
        /// </summary>
        public static string GridViewFilterAnd {
            get {
                return ResourceManager.GetString("GridViewFilterAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains.
        /// </summary>
        public static string GridViewFilterContains {
            get {
                return ResourceManager.GetString("GridViewFilterContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Contains.
        /// </summary>
        public static string GridViewFilterDoesNotContain {
            get {
                return ResourceManager.GetString("GridViewFilterDoesNotContain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ends with.
        /// </summary>
        public static string GridViewFilterEndsWith {
            get {
                return ResourceManager.GetString("GridViewFilterEndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is contained in.
        /// </summary>
        public static string GridViewFilterIsContainedIn {
            get {
                return ResourceManager.GetString("GridViewFilterIsContainedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is equal to.
        /// </summary>
        public static string GridViewFilterIsEqualTo {
            get {
                return ResourceManager.GetString("GridViewFilterIsEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is greater than.
        /// </summary>
        public static string GridViewFilterIsGreaterThan {
            get {
                return ResourceManager.GetString("GridViewFilterIsGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is greater than or equal to.
        /// </summary>
        public static string GridViewFilterIsGreaterThanOrEqualTo {
            get {
                return ResourceManager.GetString("GridViewFilterIsGreaterThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is less than.
        /// </summary>
        public static string GridViewFilterIsLessThan {
            get {
                return ResourceManager.GetString("GridViewFilterIsLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is less than or equal to.
        /// </summary>
        public static string GridViewFilterIsLessThanOrEqualTo {
            get {
                return ResourceManager.GetString("GridViewFilterIsLessThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is not contained in.
        /// </summary>
        public static string GridViewFilterIsNotContainedIn {
            get {
                return ResourceManager.GetString("GridViewFilterIsNotContainedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is not equal to.
        /// </summary>
        public static string GridViewFilterIsNotEqualTo {
            get {
                return ResourceManager.GetString("GridViewFilterIsNotEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is not null.
        /// </summary>
        public static string GridViewFilterIsNotNull {
            get {
                return ResourceManager.GetString("GridViewFilterIsNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is null.
        /// </summary>
        public static string GridViewFilterIsNull {
            get {
                return ResourceManager.GetString("GridViewFilterIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to match case.
        /// </summary>
        public static string GridViewFilterMatchCase {
            get {
                return ResourceManager.GetString("GridViewFilterMatchCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or.
        /// </summary>
        public static string GridViewFilterOr {
            get {
                return ResourceManager.GetString("GridViewFilterOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string GridViewFilterSelectAll {
            get {
                return ResourceManager.GetString("GridViewFilterSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show rows with value that.
        /// </summary>
        public static string GridViewFilterShowRowsWithValueThat {
            get {
                return ResourceManager.GetString("GridViewFilterShowRowsWithValueThat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts with.
        /// </summary>
        public static string GridViewFilterStartsWith {
            get {
                return ResourceManager.GetString("GridViewFilterStartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag a column header and drop it here to group by that column.
        /// </summary>
        public static string GridViewGroupPanelText {
            get {
                return ResourceManager.GetString("GridViewGroupPanelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Header.
        /// </summary>
        public static string GridViewGroupPanelTopText {
            get {
                return ResourceManager.GetString("GridViewGroupPanelTopText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grouped by.
        /// </summary>
        public static string GridViewGroupPanelTopTextGrouped {
            get {
                return ResourceManager.GetString("GridViewGroupPanelTopTextGrouped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        public static string Groups {
            get {
                return ResourceManager.GetString("Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H.F..
        /// </summary>
        public static string HF {
            get {
                return ResourceManager.GetString("HF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert adress.
        /// </summary>
        public static string InsertAdress {
            get {
                return ResourceManager.GetString("InsertAdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Status.
        /// </summary>
        public static string InsertStatus {
            get {
                return ResourceManager.GetString("InsertStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP.
        /// </summary>
        public static string IP {
            get {
                return ResourceManager.GetString("IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string LabelAbout {
            get {
                return ResourceManager.GetString("LabelAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string LabelClear {
            get {
                return ResourceManager.GetString("LabelClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string LabelCustomer {
            get {
                return ResourceManager.GetString("LabelCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        public static string LabelEmployee {
            get {
                return ResourceManager.GetString("LabelEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogIn.
        /// </summary>
        public static string LabelLogIn {
            get {
                return ResourceManager.GetString("LabelLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        public static string LabelMap {
            get {
                return ResourceManager.GetString("LabelMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string LabelReports {
            get {
                return ResourceManager.GetString("LabelReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last application.
        /// </summary>
        public static string LastApp {
            get {
                return ResourceManager.GetString("LastApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact name.
        /// </summary>
        public static string LastNameCus {
            get {
                return ResourceManager.GetString("LastNameCus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last point.
        /// </summary>
        public static string LastPoint {
            get {
                return ResourceManager.GetString("LastPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Classification.
        /// </summary>
        public static string Level1 {
            get {
                return ResourceManager.GetString("Level1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary Classification.
        /// </summary>
        public static string Level2 {
            get {
                return ResourceManager.GetString("Level2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of employee is 5.
        /// </summary>
        public static string LimitElements {
            get {
                return ResourceManager.GetString("LimitElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List  boxs.
        /// </summary>
        public static string ListBoxs {
            get {
                return ResourceManager.GetString("ListBoxs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Reports.
        /// </summary>
        public static string ListReports {
            get {
                return ResourceManager.GetString("ListReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading......
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogIn.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo.
        /// </summary>
        public static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail.
        /// </summary>
        public static string Mail {
            get {
                return ResourceManager.GetString("Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacture.
        /// </summary>
        public static string Manufacture {
            get {
                return ResourceManager.GetString("Manufacture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type map provider.
        /// </summary>
        public static string MapProvider {
            get {
                return ResourceManager.GetString("MapProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS message was sent successfully.
        /// </summary>
        public static string MessageSendSMS {
            get {
                return ResourceManager.GetString("MessageSendSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min. distanation.
        /// </summary>
        public static string MinDistanation {
            get {
                return ResourceManager.GetString("MinDistanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min stop time.
        /// </summary>
        public static string MinStopTime {
            get {
                return ResourceManager.GetString("MinStopTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting time.
        /// </summary>
        public static string MitingTime {
            get {
                return ResourceManager.GetString("MitingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mon.
        /// </summary>
        public static string Mon {
            get {
                return ResourceManager.GetString("Mon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message History.
        /// </summary>
        public static string MsgHistory {
            get {
                return ResourceManager.GetString("MsgHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi.
        /// </summary>
        public static string Multi {
            get {
                return ResourceManager.GetString("Multi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New customer.
        /// </summary>
        public static string NewCustomer {
            get {
                return ResourceManager.GetString("NewCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New employee.
        /// </summary>
        public static string NewEmployee {
            get {
                return ResourceManager.GetString("NewEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Visit.
        /// </summary>
        public static string NextVisit {
            get {
                return ResourceManager.GetString("NextVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Active.
        /// </summary>
        public static string NotActive {
            get {
                return ResourceManager.GetString("NotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string Number1 {
            get {
                return ResourceManager.GetString("Number1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OKBut {
            get {
                return ResourceManager.GetString("OKBut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Page.
        /// </summary>
        public static string PageCompany {
            get {
                return ResourceManager.GetString("PageCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        public static string Parameters {
            get {
                return ResourceManager.GetString("Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone1.
        /// </summary>
        public static string Phone1 {
            get {
                return ResourceManager.GetString("Phone1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone2.
        /// </summary>
        public static string Phone2 {
            get {
                return ResourceManager.GetString("Phone2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhoneType.
        /// </summary>
        public static string PhoneType {
            get {
                return ResourceManager.GetString("PhoneType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary Customer Note.
        /// </summary>
        public static string Remark1 {
            get {
                return ResourceManager.GetString("Remark1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Comment.
        /// </summary>
        public static string Remark2 {
            get {
                return ResourceManager.GetString("Remark2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Parameters.
        /// </summary>
        public static string ReportParameters {
            get {
                return ResourceManager.GetString("ReportParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request.
        /// </summary>
        public static string Request {
            get {
                return ResourceManager.GetString("Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result Search.
        /// </summary>
        public static string ResultSearch {
            get {
                return ResourceManager.GetString("ResultSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אופציה מפה עם\בלי routing.
        /// </summary>
        public static string Routing {
            get {
                return ResourceManager.GetString("Routing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sat.
        /// </summary>
        public static string Sat {
            get {
                return ResourceManager.GetString("Sat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Failed.
        /// </summary>
        public static string SaveFailed {
            get {
                return ResourceManager.GetString("SaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Ok.
        /// </summary>
        public static string SaveOk {
            get {
                return ResourceManager.GetString("SaveOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduler.
        /// </summary>
        public static string Scheduler {
            get {
                return ResourceManager.GetString("Scheduler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SearchCustomer.
        /// </summary>
        public static string SearchCustomer {
            get {
                return ResourceManager.GetString("SearchCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search with params.
        /// </summary>
        public static string SearchParams {
            get {
                return ResourceManager.GetString("SearchParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Result.
        /// </summary>
        public static string SearchResult {
            get {
                return ResourceManager.GetString("SearchResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Employee.
        /// </summary>
        public static string SelectEmployee {
            get {
                return ResourceManager.GetString("SelectEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Application.
        /// </summary>
        public static string SendApp {
            get {
                return ResourceManager.GetString("SendApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Link Application  Error.
        /// </summary>
        public static string SendLinkAppError {
            get {
                return ResourceManager.GetString("SendLinkAppError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application has been sent.
        /// </summary>
        public static string SendLinkAppOk {
            get {
                return ResourceManager.GetString("SendLinkAppOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send SMS.
        /// </summary>
        public static string SendSMS {
            get {
                return ResourceManager.GetString("SendSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שליחת הודעות התחלה / הפסק תוכנה.
        /// </summary>
        public static string SendSmsStartStop {
            get {
                return ResourceManager.GetString("SendSmsStartStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Outlook.
        /// </summary>
        public static string ServerOutlook {
            get {
                return ResourceManager.GetString("ServerOutlook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Below.
        /// </summary>
        public static string ShowBelow {
            get {
                return ResourceManager.GetString("ShowBelow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Full Screen.
        /// </summary>
        public static string ShowBelowFullWin {
            get {
                return ResourceManager.GetString("ShowBelowFullWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runway Show.
        /// </summary>
        public static string ShowFullWay {
            get {
                return ResourceManager.GetString("ShowFullWay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Map.
        /// </summary>
        public static string ShowMap {
            get {
                return ResourceManager.GetString("ShowMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Report.
        /// </summary>
        public static string ShowReport {
            get {
                return ResourceManager.GetString("ShowReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show With Customers.
        /// </summary>
        public static string ShowWithCustomers {
            get {
                return ResourceManager.GetString("ShowWithCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sinchronization.
        /// </summary>
        public static string Sinchronization {
            get {
                return ResourceManager.GetString("Sinchronization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single.
        /// </summary>
        public static string Single {
            get {
                return ResourceManager.GetString("Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS.
        /// </summary>
        public static string SMS {
            get {
                return ResourceManager.GetString("SMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS Description.
        /// </summary>
        public static string SMSDesc {
            get {
                return ResourceManager.GetString("SMSDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Day.
        /// </summary>
        public static string StartDay {
            get {
                return ResourceManager.GetString("StartDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time.
        /// </summary>
        public static string StartDayTime {
            get {
                return ResourceManager.GetString("StartDayTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string Status_0 {
            get {
                return ResourceManager.GetString("Status_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Customer.
        /// </summary>
        public static string Status_1 {
            get {
                return ResourceManager.GetString("Status_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Customer.
        /// </summary>
        public static string Status_2 {
            get {
                return ResourceManager.GetString("Status_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Customer.
        /// </summary>
        public static string Status_3 {
            get {
                return ResourceManager.GetString("Status_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Far Customer.
        /// </summary>
        public static string Status_4 {
            get {
                return ResourceManager.GetString("Status_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop without a Customer.
        /// </summary>
        public static string Status_stop {
            get {
                return ResourceManager.GetString("Status_stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Point.
        /// </summary>
        public static string StopPoint {
            get {
                return ResourceManager.GetString("StopPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        public static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sun.
        /// </summary>
        public static string Sun {
            get {
                return ResourceManager.GetString("Sun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test1.
        /// </summary>
        public static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop After.
        /// </summary>
        public static string TextDropAfter {
            get {
                return ResourceManager.GetString("TextDropAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop Before.
        /// </summary>
        public static string TextDropBefore {
            get {
                return ResourceManager.GetString("TextDropBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop In.
        /// </summary>
        public static string TextDropIn {
            get {
                return ResourceManager.GetString("TextDropIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop Root.
        /// </summary>
        public static string TextDropRoot {
            get {
                return ResourceManager.GetString("TextDropRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thu.
        /// </summary>
        public static string Thu {
            get {
                return ResourceManager.GetString("Thu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input / output.
        /// </summary>
        public static string Time1 {
            get {
                return ResourceManager.GetString("Time1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input / output.
        /// </summary>
        public static string Time2 {
            get {
                return ResourceManager.GetString("Time2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input / output.
        /// </summary>
        public static string Time3 {
            get {
                return ResourceManager.GetString("Time3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Hours.
        /// </summary>
        public static string TimeDiary {
            get {
                return ResourceManager.GetString("TimeDiary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeline.
        /// </summary>
        public static string Timeline {
            get {
                return ResourceManager.GetString("Timeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter time.
        /// </summary>
        public static string TimeWatermarkContent {
            get {
                return ResourceManager.GetString("TimeWatermarkContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treatment.
        /// </summary>
        public static string Treatment {
            get {
                return ResourceManager.GetString("Treatment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treatment Date.
        /// </summary>
        public static string TreatmentDate {
            get {
                return ResourceManager.GetString("TreatmentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tree.
        /// </summary>
        public static string Tree {
            get {
                return ResourceManager.GetString("Tree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tue.
        /// </summary>
        public static string Tue {
            get {
                return ResourceManager.GetString("Tue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TypeDragDrop.
        /// </summary>
        public static string TypeDragDrop {
            get {
                return ResourceManager.GetString("TypeDragDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TypeFindTree.
        /// </summary>
        public static string TypeFindTree {
            get {
                return ResourceManager.GetString("TypeFindTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string TypeMsg {
            get {
                return ResourceManager.GetString("TypeMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Adress.
        /// </summary>
        public static string UpdateAdress {
            get {
                return ResourceManager.GetString("UpdateAdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update password.
        /// </summary>
        public static string UpdatePass {
            get {
                return ResourceManager.GetString("UpdatePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Logo.
        /// </summary>
        public static string UploadLogo {
            get {
                return ResourceManager.GetString("UploadLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Time required.
        /// </summary>
        public static string ValidatingTime1 {
            get {
                return ResourceManager.GetString("ValidatingTime1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before Entering Port.
        /// </summary>
        public static string ValidatingTime2 {
            get {
                return ResourceManager.GetString("ValidatingTime2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Before The Previous Port.
        /// </summary>
        public static string ValidatingTime3 {
            get {
                return ResourceManager.GetString("ValidatingTime3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start And End Without.
        /// </summary>
        public static string ValidatingTime4 {
            get {
                return ResourceManager.GetString("ValidatingTime4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Interval.
        /// </summary>
        public static string VisitInterval {
            get {
                return ResourceManager.GetString("VisitInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit time.
        /// </summary>
        public static string VisitTime {
            get {
                return ResourceManager.GetString("VisitTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must Select a Customer.
        /// </summary>
        public static string WarnigMapCustomer {
            get {
                return ResourceManager.GetString("WarnigMapCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch without data.
        /// </summary>
        public static string WarningAddBranch {
            get {
                return ResourceManager.GetString("WarningAddBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must select address.
        /// </summary>
        public static string WarningBuilding {
            get {
                return ResourceManager.GetString("WarningBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will Undo The Changes.
        /// </summary>
        public static string WarningCancelEditEmployee {
            get {
                return ResourceManager.GetString("WarningCancelEditEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing data: state, city, street, house number.
        /// </summary>
        public static string WarningChangeAddressGoogle {
            get {
                return ResourceManager.GetString("WarningChangeAddressGoogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address change was successful.Save customer information to comlete the update.
        /// </summary>
        public static string WarningChangeBuildingNew {
            get {
                return ResourceManager.GetString("WarningChangeBuildingNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not delete branch =&gt; There are data.
        /// </summary>
        public static string WarningDeleteBranch {
            get {
                return ResourceManager.GetString("WarningDeleteBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שגיאה ברישום שינוי כתובת.
        /// </summary>
        public static string WarningErrorChangeBuilding {
            get {
                return ResourceManager.GetString("WarningErrorChangeBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee not exist.
        /// </summary>
        public static string WarningExistEmployee {
            get {
                return ResourceManager.GetString("WarningExistEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City Not Exist.
        /// </summary>
        public static string WarningFullCity {
            get {
                return ResourceManager.GetString("WarningFullCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Location Data.
        /// </summary>
        public static string WarningGPS {
            get {
                return ResourceManager.GetString("WarningGPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to date&gt;now.
        /// </summary>
        public static string WarningMapDate {
            get {
                return ResourceManager.GetString("WarningMapDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must Select An Employee.
        /// </summary>
        public static string WarningMapEmployee {
            get {
                return ResourceManager.GetString("WarningMapEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name or Password empty.
        /// </summary>
        public static string WarningString {
            get {
                return ResourceManager.GetString("WarningString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large Start Time End Time.
        /// </summary>
        public static string WarningTimeGps {
            get {
                return ResourceManager.GetString("WarningTimeGps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Content.
        /// </summary>
        public static string WarningValidation {
            get {
                return ResourceManager.GetString("WarningValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports can be viewed only using a browser.
        /// </summary>
        public static string WarninigReport {
            get {
                return ResourceManager.GetString("WarninigReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must Type a Message Or Phone No..
        /// </summary>
        public static string WarrningStringSMS {
            get {
                return ResourceManager.GetString("WarrningStringSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wed.
        /// </summary>
        public static string Wed {
            get {
                return ResourceManager.GetString("Wed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week.
        /// </summary>
        public static string Week {
            get {
                return ResourceManager.GetString("Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker days.
        /// </summary>
        public static string WorkerDays {
            get {
                return ResourceManager.GetString("WorkerDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker time.
        /// </summary>
        public static string WorkerTime {
            get {
                return ResourceManager.GetString("WorkerTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip Code.
        /// </summary>
        public static string ZipCode {
            get {
                return ResourceManager.GetString("ZipCode", resourceCulture);
            }
        }
    }
}
