//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISEEDataModel.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddressTypeTable
    {
        public AddressTypeTable()
        {
            this.GeocodeToTables = new HashSet<GeocodeToTable>();
        }
    
        public int AddressTypeTable1 { get; set; }
        public string Table { get; set; }
    
        public virtual ICollection<GeocodeToTable> GeocodeToTables { get; set; }
    }
}
