//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISEEDataModel.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgentUser
    {
        public int AgentUserPk { get; set; }
        public string User { get; set; }
        public string Password { get; set; }
        public System.Guid PasswordId { get; set; }
        public int ActiveAgent { get; set; }
        public Nullable<int> MainCountry { get; set; }
        public double MobileUserPrice { get; set; }
        public int SmsProvider { get; set; }
        public double SmsPrice { get; set; }
        public double BrowserPrice { get; set; }
        public double FactoryPrice { get; set; }
    }
}
