//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISEEDataModel.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgentToFactory
    {
        public int AgentToFactoryPk { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int AgentFk { get; set; }
        public int FactoryFk { get; set; }
    }
}
