//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISEEDataModel.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Building
    {
        public Building()
        {
            this.Customers = new HashSet<Customer>();
            this.CustomerToBuildings = new HashSet<CustomerToBuilding>();
        }
    
        public int BuildingCode { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int StatusCode { get; set; }
        public int CountryCode { get; set; }
        public int StateCode { get; set; }
        public int CityCode { get; set; }
        public int StreetCode { get; set; }
        public string Entry { get; set; }
        public string Number { get; set; }
        public string ZipCode { get; set; }
        public Nullable<double> Lat { get; set; }
        public Nullable<double> Long { get; set; }
        public string BuildingComment { get; set; }
        public Nullable<int> GisAccuracy { get; set; }
        public Nullable<int> GisSource { get; set; }
        public Nullable<int> CountTransitions { get; set; }
        public Nullable<double> AvergeDistance { get; set; }
    
        public virtual Street Street { get; set; }
        public virtual ICollection<Customer> Customers { get; set; }
        public virtual ICollection<CustomerToBuilding> CustomerToBuildings { get; set; }
    }
}
