//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISEEDataModel.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calendar
    {
        public Calendar()
        {
            this.EmployeeDiaryTimes = new HashSet<EmployeeDiaryTime>();
        }
    
        public int CalendarID { get; set; }
        public int Country { get; set; }
        public int Year { get; set; }
        public int Month { get; set; }
        public int Day { get; set; }
        public int DiaryDayStatus { get; set; }
        public int DayDesc { get; set; }
    
        public virtual CalendarStatusDay CalendarStatusDay { get; set; }
        public virtual Country Country1 { get; set; }
        public virtual DiaryDayStatu DiaryDayStatu { get; set; }
        public virtual ICollection<EmployeeDiaryTime> EmployeeDiaryTimes { get; set; }
    }
}
