//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISEEDataModel.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalendarStatusDay
    {
        public CalendarStatusDay()
        {
            this.Calendars = new HashSet<Calendar>();
            this.Holiday_old = new HashSet<Holiday_old>();
        }
    
        public int StatusId { get; set; }
        public int Daystatus { get; set; }
    
        public virtual ICollection<Calendar> Calendars { get; set; }
        public virtual ICollection<Holiday_old> Holiday_old { get; set; }
    }
}
