//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISEEDataModel.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public City()
        {
            this.CitySyns = new HashSet<CitySyn>();
            this.Streets = new HashSet<Street>();
        }
    
        public int CityCode { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int StatusCode { get; set; }
        public int CountryCode { get; set; }
        public int StateCode { get; set; }
        public string CityDesc { get; set; }
        public string CityDescEn { get; set; }
    
        public virtual State State { get; set; }
        public virtual ICollection<CitySyn> CitySyns { get; set; }
        public virtual ICollection<Street> Streets { get; set; }
    }
}
