//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISEEDataModel.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientLogoutLog
    {
        public int LogoutSysId { get; set; }
        public int EmployeeId { get; set; }
        public System.DateTime LogoutTimeUtc { get; set; }
        public int PlatformType { get; set; }
        public Nullable<int> BatteryLevel { get; set; }
        public Nullable<int> IsGpsEnabled { get; set; }
        public Nullable<int> GpsPointsDispatched { get; set; }
        public Nullable<int> SendCounter { get; set; }
    }
}
