//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISEEDataModel.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientLoginLog
    {
        public int LoginSysId { get; set; }
        public int EmployeeId { get; set; }
        public System.DateTime LoginTimeUtc { get; set; }
        public int PlatformType { get; set; }
        public int WasActiveBefore { get; set; }
        public int BatteryLevel { get; set; }
        public string UniqueIdentifier { get; set; }
        public string MobileClientVersion { get; set; }
    }
}
