//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISEEDataModel.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public Country()
        {
            this.Calendars = new HashSet<Calendar>();
            this.GeocodeToTables = new HashSet<GeocodeToTable>();
            this.Holiday_old = new HashSet<Holiday_old>();
            this.States = new HashSet<State>();
        }
    
        public int CountryCode { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CountryDesc { get; set; }
        public string CountryDescEn { get; set; }
        public double CurrentGmt { get; set; }
    
        public virtual ICollection<Calendar> Calendars { get; set; }
        public virtual ICollection<GeocodeToTable> GeocodeToTables { get; set; }
        public virtual ICollection<Holiday_old> Holiday_old { get; set; }
        public virtual ICollection<State> States { get; set; }
    }
}
