//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISEEDataModel.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerToBuilding
    {
        public int SysId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int StatusCode { get; set; }
        public int BuildingCode { get; set; }
        public int Factory { get; set; }
        public string Remark1 { get; set; }
        public string Remark2 { get; set; }
    
        public virtual Building Building { get; set; }
        public virtual Factory Factory1 { get; set; }
    }
}
