//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISEEDataModel.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiaryDayStatu
    {
        public DiaryDayStatu()
        {
            this.Calendars = new HashSet<Calendar>();
            this.EmployeeDiaryTemplates = new HashSet<EmployeeDiaryTemplate>();
        }
    
        public int DayStatus { get; set; }
        public int DayDesc { get; set; }
    
        public virtual ICollection<Calendar> Calendars { get; set; }
        public virtual ICollection<EmployeeDiaryTemplate> EmployeeDiaryTemplates { get; set; }
    }
}
