//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISEEDataModel.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeGpsStatus_old
    {
        public int EmployeeId { get; set; }
        public Nullable<System.DateTime> LastInsertTime { get; set; }
        public Nullable<int> Period { get; set; }
        public Nullable<int> GpsStatus { get; set; }
        public Nullable<int> Battery { get; set; }
        public Nullable<int> SampleRate { get; set; }
    }
}
