//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISEEDataModel.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeSmsSend
    {
        public int SmsId { get; set; }
        public System.DateTime SmsCreatDate { get; set; }
        public int EmployeeId { get; set; }
        public string SmsMsg { get; set; }
        public Nullable<int> SmsStatus { get; set; }
        public Nullable<int> SmsGroup { get; set; }
        public Nullable<int> SmsCount { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
