//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISEEDataModel.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeGroup
    {
        public EmployeeGroup()
        {
            this.EmployeeToGroups = new HashSet<EmployeeToGroup>();
        }
    
        public int EmployeeGroupId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public int FactoryId { get; set; }
        public int GroupCode { get; set; }
        public string GroupDesc { get; set; }
        public int Status { get; set; }
    
        public virtual Factory Factory { get; set; }
        public virtual ICollection<EmployeeToGroup> EmployeeToGroups { get; set; }
    }
}
