//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISEEDataModel.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeActive
    {
        public int SysId { get; set; }
        public int EmployeeId { get; set; }
        public System.DateTime LogInTime { get; set; }
        public System.DateTime LastTransmit { get; set; }
        public Nullable<System.DateTime> LastInsert { get; set; }
        public Nullable<System.DateTime> LastProcess { get; set; }
        public Nullable<int> LastEmployeeGpsLog { get; set; }
        public Nullable<int> LastEmployeeGpsPoint { get; set; }
        public Nullable<int> LastTransmitInserts { get; set; }
        public int ClientParamMode { get; set; }
        public bool UpdateNextTransmit { get; set; }
        public double CurrentGmt { get; set; }
        public string UniqueIdentifier { get; set; }
        public string BatteryLevel { get; set; }
        public int LastSendCounter { get; set; }
    }
}
