//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISEEDataModel.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeClientParams_old
    {
        public int EmployeeId { get; set; }
        public int DataSendInterval { get; set; }
        public int SampleRate { get; set; }
        public int GpsLossSleepTime { get; set; }
        public int StandSleepTime { get; set; }
    }
}
