//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISEEDataModel.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeDiaryTemplate
    {
        public int EmployeeDiaryTempId { get; set; }
        public int EmployeeId { get; set; }
        public int DayStatus { get; set; }
        public Nullable<System.TimeSpan> Start1 { get; set; }
        public Nullable<System.TimeSpan> Stop1 { get; set; }
        public Nullable<System.TimeSpan> Start2 { get; set; }
        public Nullable<System.TimeSpan> Stop2 { get; set; }
        public Nullable<int> OrderDay { get; set; }
    
        public virtual DiaryDayStatu DiaryDayStatu { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
