//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISEEDataModel.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.CustomerEmployeeContacts = new HashSet<CustomerEmployeeContact>();
            this.EmployeeDiaryTemplates = new HashSet<EmployeeDiaryTemplate>();
            this.EmployeeDiaryTimes = new HashSet<EmployeeDiaryTime>();
            this.EmployeeGpsLogs = new HashSet<EmployeeGpsLog>();
            this.EmployeeGpsPoints = new HashSet<EmployeeGpsPoint>();
            this.EmployeeSmsSends = new HashSet<EmployeeSmsSend>();
            this.EmployeeToGroups = new HashSet<EmployeeToGroup>();
            this.GpsEmployeeCustomers = new HashSet<GpsEmployeeCustomer>();
            this.MoblieApplicationRequests = new HashSet<MoblieApplicationRequest>();
        }
    
        public int EmployeeId { get; set; }
        public System.DateTime SysCreatDate { get; set; }
        public int Factory { get; set; }
        public string EmployeeNum { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> StartDay { get; set; }
        public Nullable<System.DateTime> EndDay { get; set; }
        public Nullable<int> Status { get; set; }
        public int PhoneManufactory { get; set; }
        public int PhoneType { get; set; }
        public Nullable<System.DateTime> LastSendApp { get; set; }
        public string MainAreaPhone { get; set; }
        public string MainPhone { get; set; }
        public string SecondAreaPhone { get; set; }
        public string SecondPhone { get; set; }
        public Nullable<System.Guid> EmployeeKey { get; set; }
        public string Mail { get; set; }
        public Nullable<int> CustomerLinkDistanceThreshold { get; set; }
        public Nullable<int> DefultClientParamMode { get; set; }
    
        public virtual ICollection<CustomerEmployeeContact> CustomerEmployeeContacts { get; set; }
        public virtual Factory Factory1 { get; set; }
        public virtual PhoneType PhoneType1 { get; set; }
        public virtual ICollection<EmployeeDiaryTemplate> EmployeeDiaryTemplates { get; set; }
        public virtual ICollection<EmployeeDiaryTime> EmployeeDiaryTimes { get; set; }
        public virtual ICollection<EmployeeGpsLog> EmployeeGpsLogs { get; set; }
        public virtual ICollection<EmployeeGpsPoint> EmployeeGpsPoints { get; set; }
        public virtual ICollection<EmployeeSmsSend> EmployeeSmsSends { get; set; }
        public virtual ICollection<EmployeeToGroup> EmployeeToGroups { get; set; }
        public virtual ICollection<GpsEmployeeCustomer> GpsEmployeeCustomers { get; set; }
        public virtual ICollection<MoblieApplicationRequest> MoblieApplicationRequests { get; set; }
    }
}
