//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISEEDataModel.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeExtra
    {
        public int EmployeeId { get; set; }
        public int DefultClientParamMode { get; set; }
        public string UpdateUrl { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public Nullable<int> LastLoginPlatform { get; set; }
    }
}
