//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISEEDataModel.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactoryParm
    {
        public int FactoryId { get; set; }
        public Nullable<int> StopEmployeeTime { get; set; }
        public int Country { get; set; }
        public bool SplitTime { get; set; }
        public Nullable<double> Lat { get; set; }
        public Nullable<double> Long { get; set; }
        public Nullable<int> Zoom { get; set; }
        public Nullable<int> MapProvider { get; set; }
        public Nullable<int> SmsProvider { get; set; }
        public string PhoneAreaCode { get; set; }
        public Nullable<int> VisitCompanyTime { get; set; }
        public Nullable<int> VisitCompanyTimeTolerance { get; set; }
        public Nullable<int> VisitCompanyTimeTolerancePercent { get; set; }
        public string CompanyLogo { get; set; }
        public double CurrentGmt { get; set; }
        public int CustomerLinkDistanceThreshold { get; set; }
        public Nullable<int> RadiusSearch { get; set; }
        public Nullable<int> TopEmployeeShearch { get; set; }
        public Nullable<int> ZoomSearchLevel { get; set; }
        public Nullable<int> CalendarShowRadius { get; set; }
        public Nullable<int> CalenderShowZoomLevel { get; set; }
        public Nullable<int> MapSearchModoul { get; set; }
    
        public virtual Factory Factory { get; set; }
    }
}
