//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISEEDataModel.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactoryUsePay
    {
        public int SystemUseId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int MainFactory { get; set; }
        public int Factory { get; set; }
        public int AgentFk { get; set; }
        public System.DateTime MonthUse { get; set; }
        public double MobileUserPrice { get; set; }
        public int MobileRegisteredUsers { get; set; }
        public int MobileActiveUsers { get; set; }
        public double MobileTotalUserPay { get; set; }
        public int SystemSmsSend { get; set; }
        public int UsreSmsSend { get; set; }
        public int TotalSmsUse { get; set; }
        public int SmsInBank { get; set; }
        public double SmsPrice { get; set; }
        public double TotalSmsPay { get; set; }
        public int BrowsersAllow { get; set; }
        public double BrowserPrice { get; set; }
        public double TotalBrowserPay { get; set; }
        public double FactoryPrice { get; set; }
        public double TotalPay { get; set; }
        public int IsPay { get; set; }
    }
}
