//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISEEDataModel.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactoryDistance
    {
        public int FactoryId { get; set; }
        public int CustomerLinkDistanceThreshold { get; set; }
        public int RadiusSearch { get; set; }
        public int TopEmployeeSearch { get; set; }
        public int ZoomSearchLevel { get; set; }
        public int CalendarShowRadius { get; set; }
        public int CalenderShowZoomLevel { get; set; }
        public int MapSearchModule { get; set; }
    }
}
