//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISEEDataModel.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactoryUsePrice
    {
        public int Factory { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public double MobilePriceUpdateDate { get; set; }
        public int AgentFk { get; set; }
        public double MobilePrice { get; set; }
        public System.DateTime BrowserPriceUpdateDate { get; set; }
        public double BrowserPrice { get; set; }
        public System.DateTime SmsPriceUpdateDate { get; set; }
        public double SmsPrice { get; set; }
        public int FactoryPriceUpdate { get; set; }
        public double FactoryPrice { get; set; }
    }
}
