//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISEEDataModel.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factory
    {
        public Factory()
        {
            this.Customers = new HashSet<Customer>();
            this.CustomerToBuildings = new HashSet<CustomerToBuilding>();
            this.EmployeeGroups = new HashSet<EmployeeGroup>();
            this.RequsetToFactoryLevel1 = new HashSet<RequsetToFactoryLevel1>();
            this.Employees = new HashSet<Employee>();
        }
    
        public int FactoryId { get; set; }
        public System.DateTime FactoryCreateDate { get; set; }
        public string FactoryDesc { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public System.Guid FactoryKey { get; set; }
    
        public virtual ICollection<Customer> Customers { get; set; }
        public virtual ICollection<CustomerToBuilding> CustomerToBuildings { get; set; }
        public virtual ICollection<EmployeeGroup> EmployeeGroups { get; set; }
        public virtual FactoryParm FactoryParm { get; set; }
        public virtual ICollection<RequsetToFactoryLevel1> RequsetToFactoryLevel1 { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
    }
}
