//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISEEDataModel.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Holiday_old
    {
        public int HolidayIndx { get; set; }
        public System.DateTime HoliadyDate { get; set; }
        public int StatusId { get; set; }
        public int CountryCode { get; set; }
    
        public virtual CalendarStatusDay CalendarStatusDay { get; set; }
        public virtual Country Country { get; set; }
    }
}
