//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISEEDataModel.Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ISEEEntities : DbContext
    {
        public ISEEEntities()
            : base("name=ISEEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public DbSet<AddressTypeTable> AddressTypeTables { get; set; }
        public DbSet<AgentToFactory> AgentToFactories { get; set; }
        public DbSet<AgentUser> AgentUsers { get; set; }
        public DbSet<AspNetRole> AspNetRoles { get; set; }
        public DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public DbSet<AspNetUser> AspNetUsers { get; set; }
        public DbSet<Building> Buildings { get; set; }
        public DbSet<Calendar> Calendars { get; set; }
        public DbSet<CalendarStatusDay> CalendarStatusDays { get; set; }
        public DbSet<City> Cities { get; set; }
        public DbSet<CitySyn> CitySyns { get; set; }
        public DbSet<ClientInsertLog> ClientInsertLogs { get; set; }
        public DbSet<ClientLoginLog> ClientLoginLogs { get; set; }
        public DbSet<ClientLogoutLog> ClientLogoutLogs { get; set; }
        public DbSet<ClientParamMode> ClientParamModes { get; set; }
        public DbSet<ClientWatchdogKillLog> ClientWatchdogKillLogs { get; set; }
        public DbSet<Country> Countries { get; set; }
        public DbSet<Customer> Customers { get; set; }
        public DbSet<CustomerEmployeeContact> CustomerEmployeeContacts { get; set; }
        public DbSet<CustomerRequest> CustomerRequests { get; set; }
        public DbSet<CustomerToBuilding> CustomerToBuildings { get; set; }
        public DbSet<DiaryDayStatu> DiaryDayStatus { get; set; }
        public DbSet<EmployeeActive> EmployeeActives { get; set; }
        public DbSet<EmployeeClientParams_old> EmployeeClientParams_old { get; set; }
        public DbSet<EmployeeDiarySm> EmployeeDiarySms { get; set; }
        public DbSet<EmployeeDiaryTemplate> EmployeeDiaryTemplates { get; set; }
        public DbSet<EmployeeDiaryTime> EmployeeDiaryTimes { get; set; }
        public DbSet<EmployeeExtra> EmployeeExtras { get; set; }
        public DbSet<EmployeeGpsLog> EmployeeGpsLogs { get; set; }
        public DbSet<EmployeeGpsPoint> EmployeeGpsPoints { get; set; }
        public DbSet<EmployeeGpsStatus_old> EmployeeGpsStatus_old { get; set; }
        public DbSet<EmployeeGroup> EmployeeGroups { get; set; }
        public DbSet<EmployeeSmsSend> EmployeeSmsSends { get; set; }
        public DbSet<EmployeeToGroup> EmployeeToGroups { get; set; }
        public DbSet<Factory> Factories { get; set; }
        public DbSet<FactoryDairyTemplet> FactoryDairyTemplets { get; set; }
        public DbSet<FactoryDistance> FactoryDistances { get; set; }
        public DbSet<FactoryLogo> FactoryLogoes { get; set; }
        public DbSet<FactoryParm> FactoryParms { get; set; }
        public DbSet<FactoryUsePay> FactoryUsePays { get; set; }
        public DbSet<FactoryUsePrice> FactoryUsePrices { get; set; }
        public DbSet<GeocodeToTable> GeocodeToTables { get; set; }
        public DbSet<GisSource> GisSources { get; set; }
        public DbSet<GpsEmployeeCustomer> GpsEmployeeCustomers { get; set; }
        public DbSet<GpsInputLog_old> GpsInputLog_old { get; set; }
        public DbSet<GpsParametrs_old> GpsParametrs_old { get; set; }
        public DbSet<Holiday_old> Holiday_old { get; set; }
        public DbSet<JobManager> JobManagers { get; set; }
        public DbSet<LanguageList> LanguageLists { get; set; }
        public DbSet<MainStringTable> MainStringTables { get; set; }
        public DbSet<MethodLog> MethodLogs { get; set; }
        public DbSet<MoblieApplicationRequest> MoblieApplicationRequests { get; set; }
        public DbSet<PeriodicJob> PeriodicJobs { get; set; }
        public DbSet<PhoneManufacture> PhoneManufactures { get; set; }
        public DbSet<PhoneType> PhoneTypes { get; set; }
        public DbSet<ProesssParm> ProesssParms { get; set; }
        public DbSet<RepoetStringLabel> RepoetStringLabels { get; set; }
        public DbSet<ReportCategory> ReportCategories { get; set; }
        public DbSet<ReportLocalParmeter> ReportLocalParmeters { get; set; }
        public DbSet<ReportName> ReportNames { get; set; }
        public DbSet<ReportPanel> ReportPanels { get; set; }
        public DbSet<ReportPanelType> ReportPanelTypes { get; set; }
        public DbSet<RequsetToFactoryLevel1> RequsetToFactoryLevel1 { get; set; }
        public DbSet<RequsetToFactoryLevel2> RequsetToFactoryLevel2 { get; set; }
        public DbSet<StarLinkClient> StarLinkClients { get; set; }
        public DbSet<State> States { get; set; }
        public DbSet<Street> Streets { get; set; }
        public DbSet<StreetSyn_old> StreetSyn_old { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<SystemSmsSend> SystemSmsSends { get; set; }
        public DbSet<TableTestItay_old> TableTestItay_old { get; set; }
        public DbSet<TestCalendar_old> TestCalendar_old { get; set; }
        public DbSet<TreeLocation> TreeLocations { get; set; }
        public DbSet<UserLogEntry> UserLogEntries { get; set; }
        public DbSet<TreeView> TreeViews { get; set; }
        public DbSet<Employee> Employees { get; set; }
        public DbSet<GeocodeStringResponse> GeocodeStringResponses { get; set; }
    }
}
