//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISEEDataModel.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class LanguageList
    {
        public int IdList { get; set; }
        public string LanguageDesc { get; set; }
        public string LanguageNickname { get; set; }
        public string OneUpLanguage { get; set; }
        public string OneUpLanguageNicknae { get; set; }
    }
}
