//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISEEDataModel.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class MethodLog
    {
        public int ID { get; set; }
        public System.DateTime LogUtcTime { get; set; }
        public string MethodName { get; set; }
        public int InOut { get; set; }
        public string RoleId { get; set; }
        public Nullable<int> ThreadId { get; set; }
    }
}
