//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISEEDataModel.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class MoblieApplicationRequest
    {
        public int SysId { get; set; }
        public int EmployeeId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string RandomValue { get; set; }
        public Nullable<int> PhoneManufacturId { get; set; }
        public Nullable<int> PhoneTypeCode { get; set; }
        public Nullable<System.DateTime> DownloadDate { get; set; }
        public string Version { get; set; }
        public Nullable<int> ApplicationId { get; set; }
        public string Ip { get; set; }
        public string Ip2 { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
