//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISEEDataModel.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportPanelType
    {
        public ReportPanelType()
        {
            this.ReportPanels = new HashSet<ReportPanel>();
        }
    
        public int ReportPanelTypePk { get; set; }
        public int ReportPanelFk { get; set; }
        public string ReportPanelTypeDesc { get; set; }
    
        public virtual ICollection<ReportPanel> ReportPanels { get; set; }
    }
}
