//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISEEDataModel.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportPanel
    {
        public int ReportPanelPk { get; set; }
        public int ReporNametFk { get; set; }
        public int ReportParamTypeFk { get; set; }
        public string ColumnName { get; set; }
    
        public virtual ReportName ReportName { get; set; }
        public virtual ReportPanelType ReportPanelType { get; set; }
    }
}
