//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISEEDataModel.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportLocalParmeter
    {
        public int ReportLocalParmeterPk { get; set; }
        public int ReportStringLabaleFk { get; set; }
        public Nullable<double> ParameterValue1 { get; set; }
        public Nullable<double> ParameterValue2 { get; set; }
        public Nullable<double> ParameterValue3 { get; set; }
        public Nullable<System.TimeSpan> ParameterTime1 { get; set; }
        public Nullable<System.TimeSpan> ParameterTime2 { get; set; }
        public Nullable<System.TimeSpan> ParameterTime3 { get; set; }
        public Nullable<System.DateTime> ParameterData1 { get; set; }
        public Nullable<System.DateTime> ParameterData2 { get; set; }
        public Nullable<System.DateTime> ParameterData3 { get; set; }
        public string ParameterString1 { get; set; }
        public string ParameterString2 { get; set; }
        public string ParameterString3 { get; set; }
        public string ParameterForeColor { get; set; }
        public string PartameterBackColor { get; set; }
    
        public virtual RepoetStringLabel RepoetStringLabel { get; set; }
    }
}
