//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISEEDataModel.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequsetToFactoryLevel1
    {
        public RequsetToFactoryLevel1()
        {
            this.RequsetToFactoryLevel2 = new HashSet<RequsetToFactoryLevel2>();
        }
    
        public int RequestSysIdLevel1 { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int Factory { get; set; }
        public int RequestIdLevel1 { get; set; }
        public string RequestDescCodeLevel1 { get; set; }
        public Nullable<int> RequsetOrder { get; set; }
        public int StatusCode { get; set; }
    
        public virtual Factory Factory1 { get; set; }
        public virtual ICollection<RequsetToFactoryLevel2> RequsetToFactoryLevel2 { get; set; }
    }
}
