//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISEEDataModel.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Street
    {
        public Street()
        {
            this.Buildings = new HashSet<Building>();
            this.StreetSyn_old = new HashSet<StreetSyn_old>();
        }
    
        public int StreetCode { get; set; }
        public int CountryCode { get; set; }
        public int StatusCode { get; set; }
        public int StateCode { get; set; }
        public int CityCode { get; set; }
        public System.DateTime CreatDate { get; set; }
        public string StreetDesc { get; set; }
        public string StreetDescEn { get; set; }
    
        public virtual ICollection<Building> Buildings { get; set; }
        public virtual City City { get; set; }
        public virtual ICollection<StreetSyn_old> StreetSyn_old { get; set; }
    }
}
