//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISEEDataModel.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableTestItay_old
    {
        public int ID { get; set; }
        public Nullable<double> Lat { get; set; }
        public Nullable<double> Long { get; set; }
        public Nullable<double> Accuracy { get; set; }
        public Nullable<int> Heading { get; set; }
        public Nullable<System.DateTime> GpsDate { get; set; }
        public Nullable<System.TimeSpan> GpsTime { get; set; }
        public Nullable<int> Speed { get; set; }
    }
}
