//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISEEDataModel.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class TreeView
    {
        public TreeView()
        {
            this.TreeView1 = new HashSet<TreeView>();
        }
    
        public long ID { get; set; }
        public Nullable<long> ParentID { get; set; }
        public string BranchID { get; set; }
        public Nullable<int> FactoryID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<TreeView> TreeView1 { get; set; }
        public virtual TreeView TreeView2 { get; set; }
    }
}
