//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISEEDataModel.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLogEntry
    {
        public int ID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int FactoryId { get; set; }
        public string IPAddress { get; set; }
        public Nullable<System.DateTime> UserExiteTime { get; set; }
    }
}
